### ISSUE TITLE
Segmentation fault (core dumped) error during make

### ISSUE THREAD

**Issue by mengen100** [vietanhdev/car-smart-cam#2]
~/Desktop/car-smart-cam/build$ sudo make 
[  0%] Automatic MOC and UIC for target STATIC
[  0%] Built target STATIC_autogen
[  1%] Built target STATIC
[  1%] Automatic MOC and UIC for target onnx_proto
[  1%] Built target onnx_proto_autogen
[  2%] Built target gen_onnx_proto
[  8%] Built target onnx_proto
[  9%] Automatic MOC and UIC for target nvonnxparser_plugin
[  9%] Built target nvonnxparser_plugin_autogen
[ 11%] Building CUDA object src/common/onnx_models/onnx-tensorrt/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o
Segmentation fault (core dumped)
src/common/onnx_models/onnx-tensorrt/CMakeFiles/nvonnxparser_plugin.dir/build.make:94: recipe for target 'src/common/onnx_models/onnx-tensorrt/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o' failed
make[2]: *** [src/common/onnx_models/onnx-tensorrt/CMakeFiles/nvonnxparser_plugin.dir/FancyActivation.cu.o] Error 139
CMakeFiles/Makefile2:471: recipe for target 'src/common/onnx_models/onnx-tensorrt/CMakeFiles/nvonnxparser_plugin.dir/all' failed
make[1]: *** [src/common/onnx_models/onnx-tensorrt/CMakeFiles/nvonnxparser_plugin.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vietanhdev** [comment]
Hello,
Please try to modify `GPU_ARCHS` in `CMakeLists.txt` for your GPU. For Jetson Nano, GPU_ARCHS = 53 and for my RTX 2070, GPU_ARCHS = 75. You can read these posts to find it:
- <https://www.programmersought.com/article/28125950847/>
- <https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/>
