### ISSUE TITLE
Compiling with TensorRT 7.1:   ‘createConcatPlugin’ is not a member of ‘nvinfer1::plugin’

### ISSUE THREAD

**Issue by mozcelikors** [vietanhdev/car-smart-cam#3]
Hi,
I want to compile this on newer Nvidia platforms such as Xavier NX / AGX.
Those platforms have TensorRT 7.1, very challenging to bump their entire Nvidia software ecosystem to lower versions, as they are newer Nvidia platforms and mostly lower version .deb packages are not available for them.
Are you planning on introducing support for TensorRT 7+ versions as TensorRT 5 is soon to be deprecated.
TensorRT 5 and TensorRT 7 seems to have some API differences, but I'm no expert in that, so if you could help us I'd appreciate it.

The current problem I'm getting is:
```
‘createConcatPlugin’ is not a member of ‘nvinfer1::plugin’
```
If you could tell me how to fix this in your code, it would be a great help.
A good looking resource: https://forums.developer.nvidia.com/t/jetpack4-4-tensoort7-1-error-createconcatplugin-is-not-a-member-of-nvinfer1-plugin/147296

**Comment by vietanhdev** [comment]
Hello,

TensorRT 7 has a lot of deprecated APIs and I don't think this source code can work with that version now.
I also don't have time to continue with this project soon for an upgrade. Currently, you can try to install Jetpack 4.3 or 4.2 for a lower TensorRT version. I also provide an SD card image for Jetson Nano [here](https://drive.google.com/file/d/1jg68ySnTt4Zm_hb4JVZKKWXRWkDucqUu/view).
